version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    ports:
      - 8080:8080
      - 5173:5173
    environment:
      - DB_URL=jdbc:sqlite:/app/backend/db/data.db